CREATE TABLE IF NOT EXISTS `Accounts`
(
	`Account`	VARCHAR(24) NOT NULL UNIQUE,
	`Key`		VARCHAR(4)  NOT NULL,
	`Inquiring` TINYINT(1)	NOT NULL		DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `Profiles` 
(
	`Account` VARCHAR(24)					 NOT NULL UNIQUE,
	`Name`	  VARCHAR(24)					 NOT NULL UNIQUE DEFAULT 'Unknown',
	`Age`	  INT							 NOT NULL		 DEFAULT 0,
	`Gender`  ENUM ('Male', 'Female', 'PNS') NOT NULL		 DEFAULT 'PNS',

	FOREIGN KEY (`Account`) REFERENCES `Accounts` (`Account`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `Dashboard` 
(
	`Name`	  VARCHAR(24)				 NOT NULL UNIQUE DEFAULT 'Unknown',
	`Account` VARCHAR(24)				 NOT NULL UNIQUE,
	`Status`  ENUM ('Online', 'Offline') NOT NULL		 DEFAULT 'Offline',
	`Output`  INT						 NOT NULL		 DEFAULT 0,

	FOREIGN KEY (`Account`) REFERENCES `Accounts` (`Account`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (`Name`)	REFERENCES `Profiles` (`Name`)	  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `Logs` 
(
	`Timestamp` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`Account`	VARCHAR(24)	NOT NULL,
	`Message`	TEXT		NOT NULL,

	FOREIGN KEY (`Account`) REFERENCES `Dashboard` (`Account`) ON DELETE CASCADE ON UPDATE CASCADE
)
